if (NOT DEFINED RFT_STAGE_TARGET_FILE)
    message(FATAL_ERROR "RFT_STAGE_TARGET_FILE is required")
endif()

if (NOT DEFINED RFT_STAGE_SOURCE_DIR)
    message(FATAL_ERROR "RFT_STAGE_SOURCE_DIR is required")
endif()

if (NOT DEFINED RFT_STAGE_DIST_DIR)
    message(FATAL_ERROR "RFT_STAGE_DIST_DIR is required")
endif()

if (NOT DEFINED RFT_STAGE_RES_DIR)
    message(FATAL_ERROR "RFT_STAGE_RES_DIR is required")
endif()

file(REMOVE_RECURSE "${RFT_STAGE_DIST_DIR}")
file(MAKE_DIRECTORY "${RFT_STAGE_DIST_DIR}")

get_filename_component(RFT_STAGE_TARGET_NAME "${RFT_STAGE_TARGET_FILE}" NAME)
file(COPY_FILE "${RFT_STAGE_TARGET_FILE}" "${RFT_STAGE_DIST_DIR}/${RFT_STAGE_TARGET_NAME}" ONLY_IF_DIFFERENT)
file(COPY "${RFT_STAGE_RES_DIR}" DESTINATION "${RFT_STAGE_DIST_DIR}")

file(GLOB RFT_STAGE_DLLS LIST_DIRECTORIES FALSE "${RFT_STAGE_SOURCE_DIR}/*.dll")
if (RFT_STAGE_DLLS)
    file(COPY ${RFT_STAGE_DLLS} DESTINATION "${RFT_STAGE_DIST_DIR}")
endif()
